logging:
    level:
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: debug
            hibernate:
                type:
                    descriptor:
                        sql: trace
spring:
    datasource:
        url: jdbc:h2:~/data/chess
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    h2:
        console:
            enabled: true

handlebars:
    suffix: .html
---

spring:
    profiles: test
    datasource:
        url: jdbc:h2:mem:test